/**
 * The 62 categories of Home Nura.
 *
 * Each entry is the conceptual home of a product segment, used by
 * every generator (reviews, versus, best-for, troubleshooting) and
 * by every routing layer. Slugs are URL-immutable once indexable
 * flips to true.
 *
 * indexable: true  → category has ≥ 12 pages of content, appears
 *                    in sitemap, routed in middleware, ranked.
 * indexable: false → category is typed and ready to receive
 *                    generated content. Hub route returns notFound()
 *                    until the depth gate is cleared.
 *
 * Phase Y baseline (what's actually shipping):
 *   - cuisine-connectee: 6 categories indexable (inherited from
 *     legacy state: airfryers, multicuiseurs, cafetieres, balances,
 *     thermometres-viande, prises-connectees).
 *   - Everything else: typed, definition-only, not routed yet.
 *
 * NOTE: prises-connectees currently lives under cuisine-connectee
 * for historical reasons. A Phase Z migration will move it to
 * energie-domotique with a 301 redirect. Until then, we keep it
 * where the site actually serves it from.
 */

import type { Category } from './types'

export const CATEGORIES: readonly Category[] = [
  // =================================================================
  // Meta-silo 1 — cuisine-connectee (flagship, 14 categories)
  // =================================================================
  {
    slug: 'airfryers',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Airfryers',
      en: 'Air Fryers',
      de: 'Heißluftfritteusen',
      es: 'Freidoras de Aire',
      it: 'Friggitrici ad Aria',
      nl: 'Airfryers',
    },
    description: {
      fr: 'Friteuses à air comparées sur 6 marchés européens : Ninja, Philips, Cosori, Xiaomi et plus.',
      en: 'Air fryers compared across 6 European markets: Ninja, Philips, Cosori, Xiaomi and more.',
      de: 'Heißluftfritteusen im Vergleich über 6 europäische Märkte: Ninja, Philips, Cosori, Xiaomi und mehr.',
      es: 'Freidoras de aire comparadas en 6 mercados europeos: Ninja, Philips, Cosori, Xiaomi y más.',
      it: 'Friggitrici ad aria confrontate su 6 mercati europei: Ninja, Philips, Cosori, Xiaomi e altro.',
      nl: 'Airfryers vergeleken over 6 Europese markten: Ninja, Philips, Cosori, Xiaomi en meer.',
    },
    primaryKeyword: {
      fr: 'meilleur airfryer',
      en: 'best air fryer',
      de: 'beste heißluftfritteuse',
      es: 'mejor freidora de aire',
      it: 'migliore friggitrice ad aria',
      nl: 'beste airfryer',
    },
  },
  {
    slug: 'multicuiseurs',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Multicuiseurs',
      en: 'Multicookers',
      de: 'Multikocher',
      es: 'Multicocinas',
      it: 'Multicooker',
      nl: 'Multicookers',
    },
    description: {
      fr: 'Multicuiseurs connectés : Instant Pot, Moulinex Cookeo, Tefal et plus.',
      en: 'Smart multicookers: Instant Pot, Moulinex Cookeo, Tefal and more.',
      de: 'Vernetzte Multikocher: Instant Pot, Moulinex Cookeo, Tefal und mehr.',
      es: 'Multicocinas conectadas: Instant Pot, Moulinex Cookeo, Tefal y más.',
      it: 'Multicooker connessi: Instant Pot, Moulinex Cookeo, Tefal e altro.',
      nl: 'Slimme multicookers: Instant Pot, Moulinex Cookeo, Tefal en meer.',
    },
    primaryKeyword: {
      fr: 'meilleur multicuiseur',
      en: 'best multicooker',
      de: 'bester multikocher',
      es: 'mejor multicocina',
      it: 'migliore multicooker',
      nl: 'beste multicooker',
    },
  },
  {
    slug: 'cafetieres',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Cafetières Connectées',
      en: 'Smart Coffee Machines',
      de: 'Vernetzte Kaffeemaschinen',
      es: 'Cafeteras Conectadas',
      it: 'Caffettiere Connesse',
      nl: 'Slimme Koffiezetapparaten',
    },
    description: {
      fr: 'Cafetières connectées à expresso, grain ou capsule, pilotables depuis un smartphone.',
      en: 'Smart espresso, bean-to-cup and capsule coffee machines controllable from your phone.',
      de: 'Vernetzte Espresso-, Kaffeevollautomaten und Kapselmaschinen per Smartphone steuerbar.',
      es: 'Cafeteras conectadas espresso, de grano y cápsulas, controlables desde el smartphone.',
      it: 'Caffettiere connesse espresso, a chicchi e a capsule, pilotabili da smartphone.',
      nl: 'Slimme espresso-, bonen- en capsule-koffiezetapparaten bestuurbaar vanaf je smartphone.',
    },
    primaryKeyword: {
      fr: 'meilleure cafetière connectée',
      en: 'best smart coffee machine',
      de: 'beste vernetzte kaffeemaschine',
      es: 'mejor cafetera conectada',
      it: 'migliore caffettiera connessa',
      nl: 'beste slimme koffiezetapparaat',
    },
  },
  {
    slug: 'balances',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Balances de Cuisine Connectées',
      en: 'Smart Kitchen Scales',
      de: 'Vernetzte Küchenwaagen',
      es: 'Básculas de Cocina Conectadas',
      it: 'Bilance da Cucina Connesse',
      nl: 'Slimme Keukenweegschalen',
    },
    description: {
      fr: 'Balances de cuisine connectées avec app nutritionnelle et recettes intégrées.',
      en: 'Smart kitchen scales with nutrition apps and built-in recipes.',
      de: 'Vernetzte Küchenwaagen mit Ernährungs-App und integrierten Rezepten.',
      es: 'Básculas de cocina conectadas con app nutricional y recetas integradas.',
      it: 'Bilance da cucina connesse con app nutrizionale e ricette integrate.',
      nl: 'Slimme keukenweegschalen met voedings-app en ingebouwde recepten.',
    },
    primaryKeyword: {
      fr: 'balance de cuisine connectée',
      en: 'smart kitchen scale',
      de: 'vernetzte küchenwaage',
      es: 'báscula de cocina conectada',
      it: 'bilancia da cucina connessa',
      nl: 'slimme keukenweegschaal',
    },
  },
  {
    slug: 'thermometres-viande',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Thermomètres à Viande Connectés',
      en: 'Smart Meat Thermometers',
      de: 'Vernetzte Fleischthermometer',
      es: 'Termómetros de Carne Conectados',
      it: 'Termometri per Carne Connessi',
      nl: 'Slimme Vleesthermometers',
    },
    description: {
      fr: 'Thermomètres à viande Bluetooth et wifi : Meater, Inkbird, ThermoPro et plus.',
      en: 'Bluetooth and Wi-Fi meat thermometers: Meater, Inkbird, ThermoPro and more.',
      de: 'Bluetooth- und WLAN-Fleischthermometer: Meater, Inkbird, ThermoPro und mehr.',
      es: 'Termómetros de carne Bluetooth y Wi-Fi: Meater, Inkbird, ThermoPro y más.',
      it: 'Termometri per carne Bluetooth e Wi-Fi: Meater, Inkbird, ThermoPro e altro.',
      nl: 'Bluetooth- en wifi-vleesthermometers: Meater, Inkbird, ThermoPro en meer.',
    },
    primaryKeyword: {
      fr: 'thermomètre à viande connecté',
      en: 'smart meat thermometer',
      de: 'vernetztes fleischthermometer',
      es: 'termómetro de carne conectado',
      it: 'termometro per carne connesso',
      nl: 'slimme vleesthermometer',
    },
  },
  {
    // Historical placement — migrates to energie-domotique in Phase Z
    // with a 301 redirect. Kept in cuisine-connectee today because
    // that's where the live route serves it from.
    slug: 'prises-connectees',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Prises Connectées',
      en: 'Smart Plugs',
      de: 'Smarte Steckdosen',
      es: 'Enchufes Inteligentes',
      it: 'Prese Intelligenti',
      nl: 'Slimme Stekkers',
    },
    description: {
      fr: 'Prises connectées pour automatiser et mesurer la consommation de tous vos appareils.',
      en: 'Smart plugs to automate and measure the consumption of every appliance.',
      de: 'Smarte Steckdosen zur Automatisierung und Verbrauchsmessung aller Geräte.',
      es: 'Enchufes inteligentes para automatizar y medir el consumo de todos tus aparatos.',
      it: 'Prese intelligenti per automatizzare e misurare il consumo di ogni apparecchio.',
      nl: 'Slimme stekkers om het verbruik van al je apparaten te automatiseren en meten.',
    },
    primaryKeyword: {
      fr: 'meilleure prise connectée',
      en: 'best smart plug',
      de: 'beste smarte steckdose',
      es: 'mejor enchufe inteligente',
      it: 'migliore presa intelligente',
      nl: 'beste slimme stekker',
    },
  },
  {
    slug: 'robots-multifonctions',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'high',
    indexable: false,
    title: {
      fr: 'Robots Multifonctions',
      en: 'Kitchen Robot Cookers',
      de: 'Küchenmaschinen mit Kochfunktion',
      es: 'Robots de Cocina Multifunción',
      it: 'Robot da Cucina Multifunzione',
      nl: 'Multifunctionele Keukenrobots',
    },
    description: {
      fr: 'Robots cuiseurs type Thermomix : Magimix Cook Expert, Moulinex i-Companion, Lidl Monsieur Cuisine.',
      en: 'Thermomix-style robot cookers: Magimix Cook Expert, Moulinex i-Companion, Lidl Monsieur Cuisine.',
      de: 'Küchenmaschinen à la Thermomix: Magimix, Moulinex Companion, Lidl Monsieur Cuisine.',
      es: 'Robots de cocina tipo Thermomix: Magimix, Moulinex Companion, Lidl Monsieur Cuisine.',
      it: 'Robot da cucina tipo Bimby: Magimix, Moulinex Companion, Lidl Monsieur Cuisine.',
      nl: 'Thermomix-achtige keukenrobots: Magimix, Moulinex Companion, Lidl Monsieur Cuisine.',
    },
    primaryKeyword: {
      fr: 'meilleur robot cuiseur',
      en: 'best kitchen robot cooker',
      de: 'beste küchenmaschine mit kochfunktion',
      es: 'mejor robot de cocina',
      it: 'migliore robot da cucina',
      nl: 'beste keukenrobot',
    },
  },
  {
    slug: 'blenders',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'medium',
    indexable: false,
    title: {
      fr: 'Blenders Haute Performance',
      en: 'High-Performance Blenders',
      de: 'Hochleistungsmixer',
      es: 'Batidoras de Alto Rendimiento',
      it: 'Frullatori ad Alte Prestazioni',
      nl: 'Krachtige Blenders',
    },
    description: {
      fr: 'Blenders Vitamix, NutriBullet, Ninja et concurrents pour smoothies et soupes.',
      en: 'Vitamix, NutriBullet, Ninja and rival blenders for smoothies and soups.',
      de: 'Mixer von Vitamix, NutriBullet, Ninja und Konkurrenz für Smoothies und Suppen.',
      es: 'Batidoras Vitamix, NutriBullet, Ninja y rivales para smoothies y sopas.',
      it: 'Frullatori Vitamix, NutriBullet, Ninja e concorrenti per smoothie e zuppe.',
      nl: 'Blenders van Vitamix, NutriBullet, Ninja en concurrenten voor smoothies en soepen.',
    },
    primaryKeyword: {
      fr: 'meilleur blender',
      en: 'best blender',
      de: 'bester mixer',
      es: 'mejor batidora',
      it: 'migliore frullatore',
      nl: 'beste blender',
    },
  },
  {
    slug: 'fours-connectes',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'medium',
    indexable: false,
    title: {
      fr: 'Fours Connectés & Vapeur',
      en: 'Smart & Steam Ovens',
      de: 'Smarte Öfen & Dampfgarer',
      es: 'Hornos Conectados y de Vapor',
      it: 'Forni Connessi e a Vapore',
      nl: 'Slimme en Stoomovens',
    },
    description: {
      fr: 'Fours connectés, fours vapeur et fours combinés des grandes marques européennes.',
      en: 'Smart, steam and combi ovens from top European brands.',
      de: 'Smarte Öfen, Dampfgarer und Kombigeräte europäischer Topmarken.',
      es: 'Hornos conectados, de vapor y combinados de marcas europeas líderes.',
      it: 'Forni connessi, a vapore e combinati dai migliori marchi europei.',
      nl: 'Slimme, stoom- en combi-ovens van topmerken uit Europa.',
    },
    primaryKeyword: {
      fr: 'meilleur four connecté',
      en: 'best smart oven',
      de: 'bester smarter backofen',
      es: 'mejor horno conectado',
      it: 'migliore forno connesso',
      nl: 'beste slimme oven',
    },
  },
  {
    slug: 'micro-ondes',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'low',
    indexable: false,
    title: {
      fr: 'Micro-ondes Connectés',
      en: 'Smart Microwaves',
      de: 'Smarte Mikrowellen',
      es: 'Microondas Conectados',
      it: 'Forni a Microonde Connessi',
      nl: 'Slimme Magnetrons',
    },
    description: {
      fr: 'Micro-ondes connectés avec pilotage vocal et programmes automatiques.',
      en: 'Smart microwaves with voice control and automatic cooking programmes.',
      de: 'Smarte Mikrowellen mit Sprachsteuerung und automatischen Programmen.',
      es: 'Microondas conectados con control por voz y programas automáticos.',
      it: 'Forni a microonde connessi con controllo vocale e programmi automatici.',
      nl: 'Slimme magnetrons met spraakbesturing en automatische programma\'s.',
    },
    primaryKeyword: {
      fr: 'micro-ondes connecté',
      en: 'smart microwave',
      de: 'smarte mikrowelle',
      es: 'microondas conectado',
      it: 'microonde connesso',
      nl: 'slimme magnetron',
    },
  },
  {
    slug: 'sous-vide',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'low',
    indexable: false,
    title: {
      fr: 'Cuisson Sous-Vide',
      en: 'Sous-Vide Cookers',
      de: 'Sous-Vide-Garer',
      es: 'Cocinado al Vacío',
      it: 'Cottura Sottovuoto',
      nl: 'Sous-Vide Apparaten',
    },
    description: {
      fr: 'Thermoplongeurs et machines sous-vide connectés pour la cuisson basse température.',
      en: 'Connected immersion circulators and sous-vide machines for low-temperature cooking.',
      de: 'Vernetzte Sous-Vide-Sticks und -Geräte für Niedrigtemperaturgaren.',
      es: 'Circuladores de inmersión y máquinas al vacío conectadas para baja temperatura.',
      it: 'Roner e macchine sottovuoto connesse per cottura a bassa temperatura.',
      nl: 'Verbonden dompelcirculatoren en sous-vide machines voor lagetemperatuurkoken.',
    },
    primaryKeyword: {
      fr: 'machine sous-vide connectée',
      en: 'smart sous-vide cooker',
      de: 'vernetzter sous-vide garer',
      es: 'máquina sous-vide conectada',
      it: 'roner connesso',
      nl: 'slimme sous-vide',
    },
  },
  {
    slug: 'machines-a-pain',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'low',
    indexable: false,
    title: {
      fr: 'Machines à Pain',
      en: 'Bread Makers',
      de: 'Brotbackautomaten',
      es: 'Máquinas de Pan',
      it: 'Macchine del Pane',
      nl: 'Broodbakmachines',
    },
    description: {
      fr: 'Machines à pain connectées : Panasonic, Moulinex, Kenwood et plus.',
      en: 'Smart bread makers: Panasonic, Moulinex, Kenwood and more.',
      de: 'Vernetzte Brotbackautomaten: Panasonic, Moulinex, Kenwood und mehr.',
      es: 'Máquinas de pan conectadas: Panasonic, Moulinex, Kenwood y más.',
      it: 'Macchine del pane connesse: Panasonic, Moulinex, Kenwood e altro.',
      nl: 'Slimme broodbakmachines: Panasonic, Moulinex, Kenwood en meer.',
    },
    primaryKeyword: {
      fr: 'meilleure machine à pain',
      en: 'best bread maker',
      de: 'bester brotbackautomat',
      es: 'mejor máquina de pan',
      it: 'migliore macchina del pane',
      nl: 'beste broodbakmachine',
    },
  },
  {
    slug: 'extracteurs-de-jus',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'low',
    indexable: false,
    title: {
      fr: 'Extracteurs de Jus',
      en: 'Slow Juicers',
      de: 'Slow Juicer',
      es: 'Extractores de Jugo',
      it: 'Estrattori di Succo',
      nl: 'Slowjuicers',
    },
    description: {
      fr: 'Extracteurs à vis lente pour jus de fruits et légumes maison.',
      en: 'Slow masticating juicers for home-made fruit and vegetable juices.',
      de: 'Entsafter mit langsamer Presstechnik für frische Säfte zu Hause.',
      es: 'Extractores de prensado lento para zumos frescos caseros.',
      it: 'Estrattori a vite lenta per succhi freschi di frutta e verdura.',
      nl: 'Slowjuicers voor verse sappen van fruit en groente thuis.',
    },
    primaryKeyword: {
      fr: 'meilleur extracteur de jus',
      en: 'best slow juicer',
      de: 'bester slow juicer',
      es: 'mejor extractor de jugo',
      it: 'migliore estrattore di succo',
      nl: 'beste slowjuicer',
    },
  },
  {
    slug: 'frigos-connectes',
    metaSilo: 'cuisine-connectee',
    searchVolume: 'high',
    indexable: false,
    reviewOnly: true,
    title: {
      fr: 'Réfrigérateurs Connectés',
      en: 'Smart Refrigerators',
      de: 'Smarte Kühlschränke',
      es: 'Frigoríficos Conectados',
      it: 'Frigoriferi Connessi',
      nl: 'Slimme Koelkasten',
    },
    description: {
      fr: 'Revues approfondies des frigos connectés Samsung Family Hub, LG InstaView et concurrents.',
      en: 'In-depth reviews of Samsung Family Hub, LG InstaView and rival smart fridges.',
      de: 'Ausführliche Tests von Samsung Family Hub, LG InstaView und anderen smarten Kühlschränken.',
      es: 'Análisis a fondo de los frigoríficos Samsung Family Hub, LG InstaView y rivales.',
      it: 'Recensioni approfondite di Samsung Family Hub, LG InstaView e rivali.',
      nl: 'Diepgaande reviews van Samsung Family Hub, LG InstaView en concurrerende slimme koelkasten.',
    },
    primaryKeyword: {
      fr: 'frigo connecté',
      en: 'smart fridge',
      de: 'smarter kühlschrank',
      es: 'frigorífico conectado',
      it: 'frigorifero connesso',
      nl: 'slimme koelkast',
    },
  },

  // =================================================================
  // Meta-silo 2 — energie-domotique (12 categories)
  // =================================================================
  {
    slug: 'thermostats',
    metaSilo: 'energie-domotique',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Thermostats Connectés',
      en: 'Smart Thermostats',
      de: 'Smarte Thermostate',
      es: 'Termostatos Inteligentes',
      it: 'Termostati Intelligenti',
      nl: 'Slimme Thermostaten',
    },
    description: {
      fr: 'Thermostats connectés Netatmo, Tado, Nest, Honeywell — réduire sa facture de chauffage.',
      en: 'Netatmo, Tado, Nest, Honeywell smart thermostats — cut your heating bill.',
      de: 'Netatmo, Tado, Nest, Honeywell smarte Thermostate — Heizkosten senken.',
      es: 'Termostatos Netatmo, Tado, Nest, Honeywell — reduce tu factura de calefacción.',
      it: 'Termostati Netatmo, Tado, Nest, Honeywell — ridurre la bolletta del riscaldamento.',
      nl: 'Netatmo, Tado, Nest, Honeywell slimme thermostaten — verlaag je stookkosten.',
    },
    primaryKeyword: {
      fr: 'meilleur thermostat connecté',
      en: 'best smart thermostat',
      de: 'bestes smartes thermostat',
      es: 'mejor termostato inteligente',
      it: 'migliore termostato intelligente',
      nl: 'beste slimme thermostaat',
    },
  },
  {
    slug: 'compteurs-energie',
    metaSilo: 'energie-domotique',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Compteurs d\'Énergie Connectés',
      en: 'Smart Energy Monitors',
      de: 'Smarte Stromzähler',
      es: 'Medidores de Energía Inteligentes',
      it: 'Monitor Energia Connessi',
      nl: 'Slimme Energiemeters',
    },
    description: {
      fr: 'Suivez la consommation électrique de votre foyer en temps réel, pièce par pièce.',
      en: 'Track your home\'s electricity use in real time, room by room.',
      de: 'Verfolgen Sie den Stromverbrauch Ihres Zuhauses in Echtzeit, Raum für Raum.',
      es: 'Controla el consumo eléctrico del hogar en tiempo real, habitación por habitación.',
      it: 'Monitora il consumo elettrico di casa in tempo reale, stanza per stanza.',
      nl: 'Volg je elektriciteitsverbruik in real time, kamer per kamer.',
    },
    primaryKeyword: {
      fr: 'compteur électrique connecté',
      en: 'smart energy monitor',
      de: 'smarter stromzähler',
      es: 'medidor de energía inteligente',
      it: 'monitor energia intelligente',
      nl: 'slimme energiemeter',
    },
  },
  {
    slug: 'solaire-balcon',
    metaSilo: 'energie-domotique',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Solaire de Balcon (Plug & Play)',
      en: 'Balcony Solar Panels',
      de: 'Balkonkraftwerke',
      es: 'Solar de Balcón Enchufable',
      it: 'Solare da Balcone',
      nl: 'Balkonzonnepanelen',
    },
    description: {
      fr: 'Kits solaires de balcon à brancher sur une prise — légal et rentable en 2026.',
      en: 'Plug-in balcony solar kits — legal and profitable in 2026.',
      de: 'Balkonkraftwerke zum Einstecken — 2026 legal und rentabel.',
      es: 'Kits solares de balcón enchufables — legales y rentables en 2026.',
      it: 'Kit solari da balcone plug-in — legali e redditizi nel 2026.',
      nl: 'Plug-in balkonzonnepanelen — legaal en rendabel in 2026.',
    },
    primaryKeyword: {
      fr: 'kit solaire balcon',
      en: 'balcony solar panel',
      de: 'balkonkraftwerk',
      es: 'kit solar balcón',
      it: 'kit solare balcone',
      nl: 'balkon zonnepaneel',
    },
  },
  {
    slug: 'batteries-domestiques',
    metaSilo: 'energie-domotique',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Batteries Domestiques',
      en: 'Home Batteries',
      de: 'Heimspeicher',
      es: 'Baterías Domésticas',
      it: 'Batterie Domestiche',
      nl: 'Thuisbatterijen',
    },
    description: {
      fr: 'Batteries de stockage solaire pour l\'autoconsommation résidentielle.',
      en: 'Solar storage batteries for residential self-consumption.',
      de: 'Solarspeicher für den Eigenverbrauch zu Hause.',
      es: 'Baterías de almacenamiento solar para autoconsumo residencial.',
      it: 'Batterie di accumulo solare per autoconsumo residenziale.',
      nl: 'Zonne-opslagbatterijen voor zelfverbruik thuis.',
    },
    primaryKeyword: {
      fr: 'batterie domestique',
      en: 'home battery',
      de: 'heimspeicher',
      es: 'batería doméstica',
      it: 'batteria domestica',
      nl: 'thuisbatterij',
    },
  },
  {
    slug: 'eclairage-connecte',
    metaSilo: 'energie-domotique',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Éclairage Connecté',
      en: 'Smart Lighting',
      de: 'Smarte Beleuchtung',
      es: 'Iluminación Inteligente',
      it: 'Illuminazione Intelligente',
      nl: 'Slimme Verlichting',
    },
    description: {
      fr: 'Ampoules et rubans LED connectés Philips Hue, IKEA Tradfri, WiZ, LIFX.',
      en: 'Smart bulbs and LED strips from Philips Hue, IKEA Tradfri, WiZ, LIFX.',
      de: 'Smarte Leuchtmittel und LED-Bänder von Philips Hue, IKEA Tradfri, WiZ, LIFX.',
      es: 'Bombillas y tiras LED inteligentes Philips Hue, IKEA Tradfri, WiZ, LIFX.',
      it: 'Lampadine e strisce LED smart Philips Hue, IKEA Tradfri, WiZ, LIFX.',
      nl: 'Slimme lampen en LED-strips van Philips Hue, IKEA Tradfri, WiZ, LIFX.',
    },
    primaryKeyword: {
      fr: 'ampoule connectée',
      en: 'smart bulb',
      de: 'smarte glühbirne',
      es: 'bombilla inteligente',
      it: 'lampadina intelligente',
      nl: 'slimme lamp',
    },
  },
  {
    slug: 'interrupteurs',
    metaSilo: 'energie-domotique',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Interrupteurs Connectés',
      en: 'Smart Switches',
      de: 'Smarte Schalter',
      es: 'Interruptores Inteligentes',
      it: 'Interruttori Intelligenti',
      nl: 'Slimme Schakelaars',
    },
    description: {
      fr: 'Interrupteurs muraux connectés Shelly, Sonoff, Legrand — y compris sans fil neutre.',
      en: 'Smart wall switches from Shelly, Sonoff, Legrand — including no-neutral-wire models.',
      de: 'Smarte Wandschalter von Shelly, Sonoff, Legrand — auch ohne Neutralleiter.',
      es: 'Interruptores inteligentes Shelly, Sonoff, Legrand — incluso sin neutro.',
      it: 'Interruttori smart Shelly, Sonoff, Legrand — anche senza neutro.',
      nl: 'Slimme wandschakelaars Shelly, Sonoff, Legrand — ook zonder nuldraad.',
    },
    primaryKeyword: {
      fr: 'interrupteur connecté',
      en: 'smart switch',
      de: 'smarter schalter',
      es: 'interruptor inteligente',
      it: 'interruttore intelligente',
      nl: 'slimme schakelaar',
    },
  },
  {
    slug: 'volets-stores',
    metaSilo: 'energie-domotique',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Volets & Stores Connectés',
      en: 'Smart Blinds & Shutters',
      de: 'Smarte Rollläden & Jalousien',
      es: 'Persianas y Estores Inteligentes',
      it: 'Tapparelle e Tende Intelligenti',
      nl: 'Slimme Rolluiken en Zonweringen',
    },
    description: {
      fr: 'Moteurs de volets et stores connectés pour automatiser l\'ouverture selon la lumière.',
      en: 'Smart blind and shutter motors to automate opening based on daylight.',
      de: 'Smarte Rollladen- und Jalousiemotoren für automatisches Öffnen nach Lichtstärke.',
      es: 'Motores de persianas y estores inteligentes para automatizar según la luz.',
      it: 'Motori smart per tapparelle e tende che si aprono in base alla luce.',
      nl: 'Slimme motoren voor rolluiken en zonwering, automatisch geopend op daglicht.',
    },
    primaryKeyword: {
      fr: 'volet roulant connecté',
      en: 'smart blinds',
      de: 'smarter rollladen',
      es: 'persiana inteligente',
      it: 'tapparella intelligente',
      nl: 'slim rolluik',
    },
  },
  {
    slug: 'capteurs-qualite-air',
    metaSilo: 'energie-domotique',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Capteurs de Qualité de l\'Air',
      en: 'Air Quality Monitors',
      de: 'Luftqualitäts-Messgeräte',
      es: 'Sensores de Calidad del Aire',
      it: 'Sensori Qualità dell\'Aria',
      nl: 'Luchtkwaliteitssensoren',
    },
    description: {
      fr: 'Détecteurs de CO₂, COV, particules fines pour surveiller l\'air de votre intérieur.',
      en: 'CO₂, VOC and particulate sensors to monitor your indoor air.',
      de: 'CO₂-, VOC- und Feinstaubsensoren für die Raumluftüberwachung.',
      es: 'Sensores de CO₂, COV y partículas para vigilar el aire interior.',
      it: 'Sensori di CO₂, COV e polveri sottili per monitorare l\'aria interna.',
      nl: 'CO₂-, VOS- en fijnstofsensoren voor binnenluchtbewaking.',
    },
    primaryKeyword: {
      fr: 'capteur qualité air',
      en: 'air quality monitor',
      de: 'luftqualitätsmessgerät',
      es: 'medidor calidad del aire',
      it: 'sensore qualità aria',
      nl: 'luchtkwaliteitsmeter',
    },
  },
  {
    slug: 'detecteurs-fuite-eau',
    metaSilo: 'energie-domotique',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Détecteurs de Fuite d\'Eau',
      en: 'Water Leak Detectors',
      de: 'Wasserleck-Melder',
      es: 'Detectores de Fugas de Agua',
      it: 'Rilevatori Perdite d\'Acqua',
      nl: 'Waterlekdetectoren',
    },
    description: {
      fr: 'Détecteurs de fuites d\'eau connectés pour éviter les dégâts des eaux coûteux.',
      en: 'Smart water leak detectors to avoid costly water damage.',
      de: 'Smarte Wasserleck-Melder zum Schutz vor teuren Wasserschäden.',
      es: 'Detectores inteligentes de fugas de agua para evitar daños costosos.',
      it: 'Rilevatori intelligenti di perdite d\'acqua per evitare danni costosi.',
      nl: 'Slimme waterlekdetectoren om dure waterschade te voorkomen.',
    },
    primaryKeyword: {
      fr: 'détecteur de fuite d\'eau',
      en: 'water leak detector',
      de: 'wassermelder',
      es: 'detector de fugas de agua',
      it: 'rilevatore perdite acqua',
      nl: 'waterlekdetector',
    },
  },
  {
    slug: 'hubs-domotique',
    metaSilo: 'energie-domotique',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Hubs Domotique',
      en: 'Smart Home Hubs',
      de: 'Smart-Home-Hubs',
      es: 'Hubs Domóticos',
      it: 'Hub Domotici',
      nl: 'Domotica Hubs',
    },
    description: {
      fr: 'Hubs Home Assistant, Jeedom, Homey, SmartThings — unifier tous vos appareils.',
      en: 'Home Assistant, Jeedom, Homey, SmartThings hubs to unify every device.',
      de: 'Home Assistant, Jeedom, Homey, SmartThings Hubs für alle Geräte unter einem Dach.',
      es: 'Hubs Home Assistant, Jeedom, Homey, SmartThings — unifica todos tus dispositivos.',
      it: 'Hub Home Assistant, Jeedom, Homey, SmartThings — unificare tutti i dispositivi.',
      nl: 'Home Assistant, Jeedom, Homey, SmartThings hubs om al je apparaten samen te brengen.',
    },
    primaryKeyword: {
      fr: 'meilleur hub domotique',
      en: 'best smart home hub',
      de: 'bester smart home hub',
      es: 'mejor hub domótico',
      it: 'migliore hub domotico',
      nl: 'beste domotica hub',
    },
  },
  {
    slug: 'bornes-recharge-ve',
    metaSilo: 'energie-domotique',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Bornes de Recharge VE',
      en: 'EV Charging Stations',
      de: 'Elektroauto-Ladestationen',
      es: 'Estaciones de Carga VE',
      it: 'Stazioni di Ricarica EV',
      nl: 'EV Laadstations',
    },
    description: {
      fr: 'Bornes de recharge domestiques pour véhicules électriques — Wallbox, EVBox, Easee.',
      en: 'Home EV charging stations — Wallbox, EVBox, Easee.',
      de: 'Heim-Ladestationen für Elektroautos — Wallbox, EVBox, Easee.',
      es: 'Estaciones de carga para coches eléctricos — Wallbox, EVBox, Easee.',
      it: 'Stazioni di ricarica domestiche per auto elettriche — Wallbox, EVBox, Easee.',
      nl: 'Thuis laadstations voor elektrische auto\'s — Wallbox, EVBox, Easee.',
    },
    primaryKeyword: {
      fr: 'borne de recharge voiture électrique',
      en: 'home ev charger',
      de: 'wallbox elektroauto',
      es: 'cargador coche eléctrico',
      it: 'wallbox auto elettrica',
      nl: 'laadpaal elektrische auto',
    },
  },

  // =================================================================
  // Meta-silo 3 — securite-maison (10 categories)
  // =================================================================
  {
    slug: 'sonnettes-video',
    metaSilo: 'securite-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Sonnettes Vidéo',
      en: 'Video Doorbells',
      de: 'Video-Türklingeln',
      es: 'Videoporteros',
      it: 'Videocitofoni',
      nl: 'Videodeurbellen',
    },
    description: {
      fr: 'Sonnettes vidéo connectées Ring, Arlo, Eufy, Reolink — voir qui sonne même en absence.',
      en: 'Ring, Arlo, Eufy, Reolink video doorbells — see who\'s at the door from anywhere.',
      de: 'Video-Türklingeln Ring, Arlo, Eufy, Reolink — von überall sehen, wer klingelt.',
      es: 'Videoporteros Ring, Arlo, Eufy, Reolink — ve quién llama desde cualquier lugar.',
      it: 'Videocitofoni Ring, Arlo, Eufy, Reolink — vedi chi suona da qualsiasi luogo.',
      nl: 'Videodeurbellen Ring, Arlo, Eufy, Reolink — zie wie er aanbelt waar je ook bent.',
    },
    primaryKeyword: {
      fr: 'meilleure sonnette vidéo',
      en: 'best video doorbell',
      de: 'beste video türklingel',
      es: 'mejor videoportero',
      it: 'migliore videocitofono',
      nl: 'beste videodeurbel',
    },
  },
  {
    slug: 'cameras-interieur',
    metaSilo: 'securite-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Caméras Intérieures',
      en: 'Indoor Cameras',
      de: 'Innenkameras',
      es: 'Cámaras Interiores',
      it: 'Telecamere per Interni',
      nl: 'Binnencamera\'s',
    },
    description: {
      fr: 'Caméras de surveillance intérieures connectées pour la maison et les animaux.',
      en: 'Smart indoor security cameras for home and pets.',
      de: 'Smarte Innenraumkameras für Zuhause und Haustiere.',
      es: 'Cámaras de vigilancia interior inteligentes para hogar y mascotas.',
      it: 'Telecamere di sorveglianza per interni smart per casa e animali.',
      nl: 'Slimme binnenbewakingscamera\'s voor huis en huisdieren.',
    },
    primaryKeyword: {
      fr: 'caméra surveillance intérieure',
      en: 'indoor security camera',
      de: 'innenüberwachungskamera',
      es: 'cámara vigilancia interior',
      it: 'telecamera sorveglianza interna',
      nl: 'binnen beveiligingscamera',
    },
  },
  {
    slug: 'cameras-exterieur',
    metaSilo: 'securite-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Caméras Extérieures',
      en: 'Outdoor Cameras',
      de: 'Außenkameras',
      es: 'Cámaras Exteriores',
      it: 'Telecamere da Esterno',
      nl: 'Buitencamera\'s',
    },
    description: {
      fr: 'Caméras de surveillance extérieures sur batterie, filaires ou solaires.',
      en: 'Battery-powered, wired and solar outdoor security cameras.',
      de: 'Akku-, kabelgebundene und solarbetriebene Außenüberwachungskameras.',
      es: 'Cámaras exteriores con batería, cableadas y solares.',
      it: 'Telecamere da esterno a batteria, cablate e solari.',
      nl: 'Buitencamera\'s op batterij, bekabeld of zonne-energie.',
    },
    primaryKeyword: {
      fr: 'caméra extérieure',
      en: 'outdoor security camera',
      de: 'außenüberwachungskamera',
      es: 'cámara exterior',
      it: 'telecamera esterna',
      nl: 'buitencamera',
    },
  },
  {
    slug: 'serrures-connectees',
    metaSilo: 'securite-maison',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Serrures Connectées',
      en: 'Smart Locks',
      de: 'Smarte Türschlösser',
      es: 'Cerraduras Inteligentes',
      it: 'Serrature Intelligenti',
      nl: 'Slimme Sloten',
    },
    description: {
      fr: 'Serrures connectées Nuki, Yale, Aqara — pour verrouiller sans clé.',
      en: 'Nuki, Yale, Aqara smart locks — keyless home access.',
      de: 'Nuki, Yale, Aqara smarte Türschlösser — schlüsselloser Zugang.',
      es: 'Cerraduras inteligentes Nuki, Yale, Aqara — acceso sin llave.',
      it: 'Serrature intelligenti Nuki, Yale, Aqara — accesso senza chiavi.',
      nl: 'Slimme sloten Nuki, Yale, Aqara — sleutelloos thuiskomen.',
    },
    primaryKeyword: {
      fr: 'serrure connectée',
      en: 'smart lock',
      de: 'smartes türschloss',
      es: 'cerradura inteligente',
      it: 'serratura intelligente',
      nl: 'slim slot',
    },
  },
  {
    slug: 'alarmes',
    metaSilo: 'securite-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Alarmes Maison',
      en: 'Home Alarm Systems',
      de: 'Alarmanlagen',
      es: 'Alarmas para el Hogar',
      it: 'Allarmi per la Casa',
      nl: 'Alarmsystemen',
    },
    description: {
      fr: 'Systèmes d\'alarme connectés sans abonnement : Somfy, Ring, Verisure, Eufy.',
      en: 'Subscription-free smart alarm systems: Somfy, Ring, Verisure, Eufy.',
      de: 'Smarte Alarmanlagen ohne Abo: Somfy, Ring, Verisure, Eufy.',
      es: 'Alarmas inteligentes sin cuota: Somfy, Ring, Verisure, Eufy.',
      it: 'Sistemi di allarme smart senza abbonamento: Somfy, Ring, Verisure, Eufy.',
      nl: 'Slimme alarmsystemen zonder abonnement: Somfy, Ring, Verisure, Eufy.',
    },
    primaryKeyword: {
      fr: 'alarme maison sans abonnement',
      en: 'home alarm no subscription',
      de: 'alarmanlage ohne abo',
      es: 'alarma sin cuota',
      it: 'allarme casa senza abbonamento',
      nl: 'alarmsysteem zonder abonnement',
    },
  },
  {
    slug: 'detecteurs-fumee-co',
    metaSilo: 'securite-maison',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Détecteurs de Fumée & CO',
      en: 'Smoke & CO Detectors',
      de: 'Rauch- & CO-Melder',
      es: 'Detectores de Humo y CO',
      it: 'Rilevatori Fumo e CO',
      nl: 'Rook- en CO-Melders',
    },
    description: {
      fr: 'Détecteurs de fumée et monoxyde de carbone connectés (DAAF NF EN 14604).',
      en: 'Smart smoke and carbon monoxide detectors certified to EN 14604.',
      de: 'Vernetzte Rauch- und CO-Melder nach EN 14604.',
      es: 'Detectores de humo y monóxido inteligentes certificados EN 14604.',
      it: 'Rilevatori di fumo e CO intelligenti certificati EN 14604.',
      nl: 'Slimme rook- en CO-melders gecertificeerd volgens EN 14604.',
    },
    primaryKeyword: {
      fr: 'détecteur fumée connecté',
      en: 'smart smoke detector',
      de: 'smarter rauchmelder',
      es: 'detector de humo inteligente',
      it: 'rilevatore fumo intelligente',
      nl: 'slimme rookmelder',
    },
  },
  {
    slug: 'detecteurs-mouvement',
    metaSilo: 'securite-maison',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Détecteurs de Mouvement',
      en: 'Motion Sensors',
      de: 'Bewegungsmelder',
      es: 'Sensores de Movimiento',
      it: 'Sensori di Movimento',
      nl: 'Bewegingssensoren',
    },
    description: {
      fr: 'Détecteurs de présence connectés pour scénarios domotiques et alarme.',
      en: 'Smart motion sensors for automation routines and alarms.',
      de: 'Smarte Bewegungsmelder für Automatisierung und Alarm.',
      es: 'Sensores de movimiento inteligentes para escenas y alarmas.',
      it: 'Sensori di movimento smart per automazioni e allarmi.',
      nl: 'Slimme bewegingssensoren voor routines en alarm.',
    },
    primaryKeyword: {
      fr: 'détecteur de mouvement connecté',
      en: 'smart motion sensor',
      de: 'smarter bewegungsmelder',
      es: 'sensor de movimiento inteligente',
      it: 'sensore di movimento intelligente',
      nl: 'slimme bewegingssensor',
    },
  },
  {
    slug: 'trackers-objets',
    metaSilo: 'securite-maison',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Trackers d\'Objets',
      en: 'Item Trackers',
      de: 'Gegenstands-Tracker',
      es: 'Localizadores de Objetos',
      it: 'Tracker per Oggetti',
      nl: 'Item Trackers',
    },
    description: {
      fr: 'AirTag, Tile, Samsung SmartTag — retrouver ses clés, sac ou vélo en 6 secondes.',
      en: 'AirTag, Tile, Samsung SmartTag — find your keys, bag or bike in seconds.',
      de: 'AirTag, Tile, Samsung SmartTag — Schlüssel, Taschen oder Fahrrad in Sekunden finden.',
      es: 'AirTag, Tile, Samsung SmartTag — encuentra llaves, bolso o bici en segundos.',
      it: 'AirTag, Tile, Samsung SmartTag — trovare chiavi, borsa o bici in pochi secondi.',
      nl: 'AirTag, Tile, Samsung SmartTag — sleutels, tas of fiets terugvinden in seconden.',
    },
    primaryKeyword: {
      fr: 'tracker objet',
      en: 'best item tracker',
      de: 'bester gegenstandsfinder',
      es: 'localizador de objetos',
      it: 'tracker oggetti',
      nl: 'beste item tracker',
    },
  },
  {
    slug: 'interphones',
    metaSilo: 'securite-maison',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Interphones Vidéo',
      en: 'Video Intercoms',
      de: 'Video-Gegensprechanlagen',
      es: 'Videoporteros IP',
      it: 'Videocitofoni IP',
      nl: 'Video Intercoms',
    },
    description: {
      fr: 'Interphones vidéo IP connectés pour maisons et immeubles.',
      en: 'IP video intercoms for houses and apartment blocks.',
      de: 'IP-Video-Gegensprechanlagen für Häuser und Mehrfamilienhäuser.',
      es: 'Videoporteros IP para casas y bloques de apartamentos.',
      it: 'Videocitofoni IP per case e condomini.',
      nl: 'IP video-intercoms voor huizen en appartementen.',
    },
    primaryKeyword: {
      fr: 'interphone vidéo connecté',
      en: 'ip video intercom',
      de: 'ip video gegensprechanlage',
      es: 'videoportero ip',
      it: 'videocitofono ip',
      nl: 'ip video intercom',
    },
  },
  {
    slug: 'coffres-forts-connectes',
    metaSilo: 'securite-maison',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Coffres-forts Connectés',
      en: 'Smart Safes',
      de: 'Smarte Tresore',
      es: 'Cajas Fuertes Conectadas',
      it: 'Casseforti Connesse',
      nl: 'Slimme Kluizen',
    },
    description: {
      fr: 'Coffres-forts biométriques connectés pour documents et objets de valeur.',
      en: 'Biometric smart safes for documents and valuables.',
      de: 'Biometrische smarte Tresore für Dokumente und Wertsachen.',
      es: 'Cajas fuertes biométricas conectadas para documentos y objetos de valor.',
      it: 'Casseforti biometriche connesse per documenti e oggetti di valore.',
      nl: 'Biometrische slimme kluizen voor documenten en waardevolle spullen.',
    },
    primaryKeyword: {
      fr: 'coffre-fort connecté',
      en: 'smart safe',
      de: 'smarter tresor',
      es: 'caja fuerte conectada',
      it: 'cassaforte connessa',
      nl: 'slimme kluis',
    },
  },

  // =================================================================
  // Meta-silo 4 — confort-air (10 categories)
  // =================================================================
  {
    slug: 'purificateurs-air',
    metaSilo: 'confort-air',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Purificateurs d\'Air',
      en: 'Air Purifiers',
      de: 'Luftreiniger',
      es: 'Purificadores de Aire',
      it: 'Purificatori d\'Aria',
      nl: 'Luchtreinigers',
    },
    description: {
      fr: 'Purificateurs Dyson, Philips, Xiaomi, Levoit testés sur les particules fines et les allergènes.',
      en: 'Dyson, Philips, Xiaomi, Levoit purifiers tested for particulates and allergens.',
      de: 'Luftreiniger von Dyson, Philips, Xiaomi, Levoit im Test gegen Feinstaub und Allergene.',
      es: 'Purificadores Dyson, Philips, Xiaomi, Levoit probados frente a partículas y alérgenos.',
      it: 'Purificatori Dyson, Philips, Xiaomi, Levoit testati su polveri sottili e allergeni.',
      nl: 'Luchtreinigers van Dyson, Philips, Xiaomi, Levoit getest op fijnstof en allergenen.',
    },
    primaryKeyword: {
      fr: 'meilleur purificateur d\'air',
      en: 'best air purifier',
      de: 'bester luftreiniger',
      es: 'mejor purificador de aire',
      it: 'migliore purificatore d\'aria',
      nl: 'beste luchtreiniger',
    },
  },
  {
    slug: 'humidificateurs',
    metaSilo: 'confort-air',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Humidificateurs Connectés',
      en: 'Smart Humidifiers',
      de: 'Smarte Luftbefeuchter',
      es: 'Humidificadores Inteligentes',
      it: 'Umidificatori Intelligenti',
      nl: 'Slimme Luchtbevochtigers',
    },
    description: {
      fr: 'Humidificateurs connectés pour maintenir un taux d\'humidité sain en hiver.',
      en: 'Smart humidifiers to keep a healthy humidity level in winter.',
      de: 'Smarte Luftbefeuchter für gesunde Raumluftfeuchte im Winter.',
      es: 'Humidificadores inteligentes para mantener una humedad sana en invierno.',
      it: 'Umidificatori intelligenti per mantenere un\'umidità sana in inverno.',
      nl: 'Slimme luchtbevochtigers voor een gezonde vochtigheid in de winter.',
    },
    primaryKeyword: {
      fr: 'meilleur humidificateur',
      en: 'best smart humidifier',
      de: 'bester luftbefeuchter',
      es: 'mejor humidificador',
      it: 'migliore umidificatore',
      nl: 'beste luchtbevochtiger',
    },
  },
  {
    slug: 'deshumidificateurs',
    metaSilo: 'confort-air',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Déshumidificateurs Connectés',
      en: 'Smart Dehumidifiers',
      de: 'Smarte Luftentfeuchter',
      es: 'Deshumidificadores Inteligentes',
      it: 'Deumidificatori Intelligenti',
      nl: 'Slimme Luchtontvochtigers',
    },
    description: {
      fr: 'Déshumidificateurs connectés contre l\'humidité, la moisissure et la condensation.',
      en: 'Smart dehumidifiers against damp, mould and condensation.',
      de: 'Smarte Luftentfeuchter gegen Feuchte, Schimmel und Kondenswasser.',
      es: 'Deshumidificadores inteligentes contra humedad, moho y condensación.',
      it: 'Deumidificatori intelligenti contro umidità, muffa e condensa.',
      nl: 'Slimme luchtontvochtigers tegen vocht, schimmel en condens.',
    },
    primaryKeyword: {
      fr: 'meilleur déshumidificateur',
      en: 'best dehumidifier',
      de: 'bester luftentfeuchter',
      es: 'mejor deshumidificador',
      it: 'migliore deumidificatore',
      nl: 'beste luchtontvochtiger',
    },
  },
  {
    slug: 'climatiseurs-mobiles',
    metaSilo: 'confort-air',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Climatiseurs Mobiles Connectés',
      en: 'Smart Portable Air Conditioners',
      de: 'Smarte Mobile Klimageräte',
      es: 'Aires Acondicionados Portátiles Conectados',
      it: 'Condizionatori Portatili Connessi',
      nl: 'Slimme Mobiele Airco\'s',
    },
    description: {
      fr: 'Climatiseurs mobiles connectés pour rafraîchir appartements et bureaux sans travaux.',
      en: 'Smart portable ACs to cool flats and offices without installation.',
      de: 'Smarte mobile Klimageräte zum Kühlen von Wohnungen und Büros ohne Installation.',
      es: 'Aires portátiles inteligentes para enfriar pisos y oficinas sin obras.',
      it: 'Condizionatori portatili intelligenti per appartamenti e uffici senza installazione.',
      nl: 'Slimme mobiele airco\'s om appartementen en kantoren te koelen zonder installatie.',
    },
    primaryKeyword: {
      fr: 'climatiseur mobile',
      en: 'portable air conditioner',
      de: 'mobiles klimagerät',
      es: 'aire acondicionado portátil',
      it: 'condizionatore portatile',
      nl: 'mobiele airco',
    },
  },
  {
    slug: 'ventilateurs',
    metaSilo: 'confort-air',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Ventilateurs Connectés',
      en: 'Smart Fans',
      de: 'Smarte Ventilatoren',
      es: 'Ventiladores Inteligentes',
      it: 'Ventilatori Intelligenti',
      nl: 'Slimme Ventilatoren',
    },
    description: {
      fr: 'Ventilateurs Dyson, Xiaomi et concurrents connectés — silencieux, efficaces, pilotables.',
      en: 'Dyson, Xiaomi and rival smart fans — quiet, efficient, app-controlled.',
      de: 'Ventilatoren von Dyson, Xiaomi und Konkurrenz — leise, effizient, per App.',
      es: 'Ventiladores Dyson, Xiaomi y rivales — silenciosos, eficientes, con app.',
      it: 'Ventilatori Dyson, Xiaomi e rivali — silenziosi, efficienti, controllabili da app.',
      nl: 'Dyson, Xiaomi en concurrerende slimme ventilatoren — stil, efficiënt, met app.',
    },
    primaryKeyword: {
      fr: 'ventilateur connecté',
      en: 'smart fan',
      de: 'smarter ventilator',
      es: 'ventilador inteligente',
      it: 'ventilatore intelligente',
      nl: 'slimme ventilator',
    },
  },
  {
    slug: 'chauffages-appoint',
    metaSilo: 'confort-air',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Chauffages d\'Appoint Connectés',
      en: 'Smart Space Heaters',
      de: 'Smarte Heizlüfter',
      es: 'Calefactores Inteligentes',
      it: 'Stufe Intelligenti',
      nl: 'Slimme Bijverwarmers',
    },
    description: {
      fr: 'Radiateurs et chauffages d\'appoint connectés pour réchauffer une pièce à la demande.',
      en: 'Smart space heaters to warm a room on demand.',
      de: 'Smarte Heizlüfter zum Aufwärmen einzelner Räume auf Abruf.',
      es: 'Calefactores inteligentes para calentar una habitación a demanda.',
      it: 'Stufette intelligenti per riscaldare una stanza su richiesta.',
      nl: 'Slimme bijverwarmers om een kamer op afroep te verwarmen.',
    },
    primaryKeyword: {
      fr: 'chauffage d\'appoint connecté',
      en: 'smart space heater',
      de: 'smarter heizlüfter',
      es: 'calefactor inteligente',
      it: 'stufa intelligente',
      nl: 'slimme bijverwarmer',
    },
  },
  {
    slug: 'stations-meteo',
    metaSilo: 'confort-air',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Stations Météo Connectées',
      en: 'Smart Weather Stations',
      de: 'Smarte Wetterstationen',
      es: 'Estaciones Meteorológicas Conectadas',
      it: 'Stazioni Meteo Connesse',
      nl: 'Slimme Weerstations',
    },
    description: {
      fr: 'Stations météo Netatmo, Bresser, La Crosse pour suivre climat intérieur et extérieur.',
      en: 'Netatmo, Bresser, La Crosse weather stations to track indoor and outdoor climate.',
      de: 'Wetterstationen von Netatmo, Bresser, La Crosse für Innen- und Außenklima.',
      es: 'Estaciones Netatmo, Bresser, La Crosse para clima interior y exterior.',
      it: 'Stazioni meteo Netatmo, Bresser, La Crosse per clima interno ed esterno.',
      nl: 'Netatmo, Bresser, La Crosse weerstations voor binnen- en buitenklimaat.',
    },
    primaryKeyword: {
      fr: 'station météo connectée',
      en: 'smart weather station',
      de: 'smarte wetterstation',
      es: 'estación meteorológica conectada',
      it: 'stazione meteo connessa',
      nl: 'slim weerstation',
    },
  },
  {
    slug: 'diffuseurs',
    metaSilo: 'confort-air',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Diffuseurs d\'Huiles Essentielles',
      en: 'Smart Essential Oil Diffusers',
      de: 'Smarte Aromadiffusoren',
      es: 'Difusores Inteligentes de Aromas',
      it: 'Diffusori Intelligenti di Oli Essenziali',
      nl: 'Slimme Aromadiffusers',
    },
    description: {
      fr: 'Diffuseurs connectés d\'huiles essentielles pour parfumer et assainir l\'air.',
      en: 'Smart essential oil diffusers for scenting and freshening the air.',
      de: 'Smarte Aromadiffusoren für einen frischen, duftenden Innenraum.',
      es: 'Difusores inteligentes de aceites esenciales para perfumar y purificar.',
      it: 'Diffusori intelligenti di oli essenziali per profumare e purificare.',
      nl: 'Slimme aromadiffusers om de lucht te geuren en fris te houden.',
    },
    primaryKeyword: {
      fr: 'diffuseur huile essentielle connecté',
      en: 'smart essential oil diffuser',
      de: 'smarter aromadiffusor',
      es: 'difusor aromas inteligente',
      it: 'diffusore oli essenziali intelligente',
      nl: 'slimme aromadiffuser',
    },
  },
  {
    slug: 'reveils-lumiere',
    metaSilo: 'confort-air',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Réveils Lumière & Luminothérapie',
      en: 'Wake-Up Lights & Lightboxes',
      de: 'Lichtwecker & Tageslichtlampen',
      es: 'Despertadores de Luz y Luminoterapia',
      it: 'Sveglie Luminose e Lampade di Luminoterapia',
      nl: 'Wake-Up Lights & Lichttherapie',
    },
    description: {
      fr: 'Réveils lumière Philips et lampes de luminothérapie contre le blues hivernal.',
      en: 'Philips wake-up lights and lightboxes to beat winter blues.',
      de: 'Philips Lichtwecker und Tageslichtlampen gegen den Winterblues.',
      es: 'Despertadores Philips y lámparas de luminoterapia contra la depresión invernal.',
      it: 'Sveglie luminose Philips e lampade di luminoterapia contro il blues invernale.',
      nl: 'Philips wake-up lights en lichttherapielampen tegen winterdip.',
    },
    primaryKeyword: {
      fr: 'réveil lumière',
      en: 'wake up light',
      de: 'lichtwecker',
      es: 'despertador de luz',
      it: 'sveglia luminosa',
      nl: 'wake up light',
    },
  },
  {
    slug: 'rideaux-automatises',
    metaSilo: 'confort-air',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Rideaux Automatisés',
      en: 'Smart Curtains',
      de: 'Smarte Vorhänge',
      es: 'Cortinas Automatizadas',
      it: 'Tende Automatizzate',
      nl: 'Slimme Gordijnen',
    },
    description: {
      fr: 'Moteurs de rideaux automatisés SwitchBot, Aqara — ouverture par horaire ou par voix.',
      en: 'SwitchBot, Aqara smart curtain motors — open by schedule or voice.',
      de: 'SwitchBot, Aqara Vorhangmotoren — nach Zeitplan oder Sprache öffnen.',
      es: 'Motores de cortinas SwitchBot, Aqara — apertura por horario o voz.',
      it: 'Motori per tende SwitchBot, Aqara — apertura a orario o con voce.',
      nl: 'SwitchBot, Aqara gordijnmotoren — openen op tijd of stem.',
    },
    primaryKeyword: {
      fr: 'rideau automatisé',
      en: 'smart curtain',
      de: 'smarter vorhang',
      es: 'cortina automatizada',
      it: 'tenda automatizzata',
      nl: 'slim gordijn',
    },
  },

  // =================================================================
  // Meta-silo 5 — entretien-maison (8 categories)
  // =================================================================
  {
    slug: 'aspirateurs-robots',
    metaSilo: 'entretien-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Aspirateurs Robots',
      en: 'Robot Vacuums',
      de: 'Saugroboter',
      es: 'Robots Aspiradores',
      it: 'Aspirapolvere Robot',
      nl: 'Robotstofzuigers',
    },
    description: {
      fr: 'Aspirateurs robots Roomba, Roborock, Dreame, Ecovacs — tests cartographie LiDAR.',
      en: 'Roomba, Roborock, Dreame, Ecovacs robot vacuums — LiDAR mapping tests.',
      de: 'Saugroboter Roomba, Roborock, Dreame, Ecovacs — LiDAR-Kartierungstests.',
      es: 'Robots aspiradores Roomba, Roborock, Dreame, Ecovacs — pruebas con LiDAR.',
      it: 'Aspirapolvere robot Roomba, Roborock, Dreame, Ecovacs — test mappatura LiDAR.',
      nl: 'Robotstofzuigers Roomba, Roborock, Dreame, Ecovacs — LiDAR mapping tests.',
    },
    primaryKeyword: {
      fr: 'meilleur aspirateur robot',
      en: 'best robot vacuum',
      de: 'bester saugroboter',
      es: 'mejor robot aspirador',
      it: 'migliore aspirapolvere robot',
      nl: 'beste robotstofzuiger',
    },
  },
  {
    slug: 'aspirateurs-laveurs',
    metaSilo: 'entretien-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Aspirateurs Laveurs Robots',
      en: 'Vacuum-Mop Robots',
      de: 'Saug-Wisch-Roboter',
      es: 'Robots Aspirador-Fregador',
      it: 'Robot Aspirapolvere-Lavapavimenti',
      nl: 'Robot Stofzuiger-Dweilers',
    },
    description: {
      fr: 'Robots 2-en-1 qui aspirent et lavent : Roborock S8, Dreame L20, Ecovacs X2.',
      en: '2-in-1 robots that vacuum and mop: Roborock S8, Dreame L20, Ecovacs X2.',
      de: '2-in-1 Roboter saugen und wischen: Roborock S8, Dreame L20, Ecovacs X2.',
      es: 'Robots 2 en 1 que aspiran y friegan: Roborock S8, Dreame L20, Ecovacs X2.',
      it: 'Robot 2 in 1 che aspirano e lavano: Roborock S8, Dreame L20, Ecovacs X2.',
      nl: '2-in-1 robots die stofzuigen en dweilen: Roborock S8, Dreame L20, Ecovacs X2.',
    },
    primaryKeyword: {
      fr: 'aspirateur laveur robot',
      en: 'vacuum mop robot',
      de: 'saug wisch roboter',
      es: 'robot aspirador fregador',
      it: 'robot aspirapolvere lavapavimenti',
      nl: 'robot stofzuiger dweiler',
    },
  },
  {
    slug: 'laveurs-vitres',
    metaSilo: 'entretien-maison',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Laveurs de Vitres Robotisés',
      en: 'Window Cleaning Robots',
      de: 'Fensterputzroboter',
      es: 'Robots Limpiacristales',
      it: 'Robot Lavavetri',
      nl: 'Raamwasrobots',
    },
    description: {
      fr: 'Robots laveurs de vitres Hobot, Ecovacs, Mamibot — nettoyage sécurisé à hauteur.',
      en: 'Hobot, Ecovacs, Mamibot window robots — safe at-height cleaning.',
      de: 'Hobot, Ecovacs, Mamibot Fensterputzroboter — sicheres Reinigen in der Höhe.',
      es: 'Robots limpiacristales Hobot, Ecovacs, Mamibot — limpieza segura en altura.',
      it: 'Robot lavavetri Hobot, Ecovacs, Mamibot — pulizia sicura in altezza.',
      nl: 'Hobot, Ecovacs, Mamibot raamwasrobots — veilig op hoogte schoonmaken.',
    },
    primaryKeyword: {
      fr: 'robot laveur de vitres',
      en: 'window cleaning robot',
      de: 'fensterputzroboter',
      es: 'robot limpiacristales',
      it: 'robot lavavetri',
      nl: 'raamwasrobot',
    },
  },
  {
    slug: 'aspirateurs-balais',
    metaSilo: 'entretien-maison',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Aspirateurs Balais Sans Fil',
      en: 'Cordless Stick Vacuums',
      de: 'Akku-Stielsauger',
      es: 'Aspiradores Escoba Sin Cable',
      it: 'Scope Elettriche a Batteria',
      nl: 'Snoerloze Steelstofzuigers',
    },
    description: {
      fr: 'Aspirateurs balais Dyson, Samsung, Dreame, Xiaomi avec app de suivi filtre.',
      en: 'Dyson, Samsung, Dreame, Xiaomi stick vacuums with filter-tracking apps.',
      de: 'Dyson, Samsung, Dreame, Xiaomi Stielsauger mit App-Filterüberwachung.',
      es: 'Aspiradores Dyson, Samsung, Dreame, Xiaomi con app de seguimiento de filtros.',
      it: 'Scope Dyson, Samsung, Dreame, Xiaomi con app monitoraggio filtri.',
      nl: 'Dyson, Samsung, Dreame, Xiaomi steelstofzuigers met filter-app.',
    },
    primaryKeyword: {
      fr: 'meilleur aspirateur balai',
      en: 'best cordless stick vacuum',
      de: 'bester akku stielsauger',
      es: 'mejor aspirador escoba',
      it: 'migliore scopa elettrica',
      nl: 'beste steelstofzuiger',
    },
  },
  {
    slug: 'nettoyeurs-vapeur',
    metaSilo: 'entretien-maison',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Nettoyeurs Vapeur',
      en: 'Steam Cleaners',
      de: 'Dampfreiniger',
      es: 'Limpiadoras a Vapor',
      it: 'Pulitori a Vapore',
      nl: 'Stoomreinigers',
    },
    description: {
      fr: 'Nettoyeurs vapeur Kärcher, Polti, Black+Decker pour sols, vitres et sanitaires.',
      en: 'Kärcher, Polti, Black+Decker steam cleaners for floors, windows and bathrooms.',
      de: 'Kärcher, Polti, Black+Decker Dampfreiniger für Böden, Fenster und Bäder.',
      es: 'Limpiadoras a vapor Kärcher, Polti, Black+Decker para suelos, ventanas y baños.',
      it: 'Pulitori a vapore Kärcher, Polti, Black+Decker per pavimenti, vetri e bagni.',
      nl: 'Kärcher, Polti, Black+Decker stoomreinigers voor vloeren, ramen en badkamers.',
    },
    primaryKeyword: {
      fr: 'meilleur nettoyeur vapeur',
      en: 'best steam cleaner',
      de: 'bester dampfreiniger',
      es: 'mejor limpiadora vapor',
      it: 'migliore pulitore a vapore',
      nl: 'beste stoomreiniger',
    },
  },
  {
    slug: 'fers-centrales-vapeur',
    metaSilo: 'entretien-maison',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Fers & Centrales Vapeur',
      en: 'Irons & Steam Generators',
      de: 'Bügeleisen & Dampfbügelstationen',
      es: 'Planchas y Centros de Planchado',
      it: 'Ferri e Sistemi Stiranti',
      nl: 'Strijkijzers en Stoomgeneratoren',
    },
    description: {
      fr: 'Centrales vapeur Philips, Calor, Rowenta et plus pour un repassage éclair.',
      en: 'Philips, Calor, Rowenta steam generators for lightning-fast ironing.',
      de: 'Philips, Calor, Rowenta Dampfbügelstationen für blitzschnelles Bügeln.',
      es: 'Centros de planchado Philips, Calor, Rowenta para planchar en un suspiro.',
      it: 'Sistemi stiranti Philips, Calor, Rowenta per una stiratura lampo.',
      nl: 'Philips, Calor, Rowenta stoomgeneratoren voor razendsnel strijken.',
    },
    primaryKeyword: {
      fr: 'meilleure centrale vapeur',
      en: 'best steam generator iron',
      de: 'beste dampfbügelstation',
      es: 'mejor centro de planchado',
      it: 'migliore sistema stirante',
      nl: 'beste stoomgenerator',
    },
  },
  {
    slug: 'lave-vaisselle-connectes',
    metaSilo: 'entretien-maison',
    searchVolume: 'medium',
    indexable: true,
    reviewOnly: true,
    title: {
      fr: 'Lave-vaisselle Connectés',
      en: 'Smart Dishwashers',
      de: 'Smarte Geschirrspüler',
      es: 'Lavavajillas Conectados',
      it: 'Lavastoviglie Connesse',
      nl: 'Slimme Vaatwassers',
    },
    description: {
      fr: 'Revues des lave-vaisselle connectés Bosch, Siemens, Miele, Samsung.',
      en: 'Reviews of Bosch, Siemens, Miele, Samsung smart dishwashers.',
      de: 'Tests smarter Geschirrspüler von Bosch, Siemens, Miele, Samsung.',
      es: 'Análisis de lavavajillas conectados Bosch, Siemens, Miele, Samsung.',
      it: 'Recensioni lavastoviglie connesse Bosch, Siemens, Miele, Samsung.',
      nl: 'Reviews van slimme vaatwassers Bosch, Siemens, Miele, Samsung.',
    },
    primaryKeyword: {
      fr: 'lave-vaisselle connecté',
      en: 'smart dishwasher',
      de: 'smarter geschirrspüler',
      es: 'lavavajillas conectado',
      it: 'lavastoviglie connessa',
      nl: 'slimme vaatwasser',
    },
  },
  {
    slug: 'lave-linge-connectes',
    metaSilo: 'entretien-maison',
    searchVolume: 'high',
    indexable: true,
    reviewOnly: true,
    title: {
      fr: 'Lave-linge & Sèche-linge Connectés',
      en: 'Smart Washers & Dryers',
      de: 'Smarte Waschmaschinen & Trockner',
      es: 'Lavadoras y Secadoras Conectadas',
      it: 'Lavatrici e Asciugatrici Connesse',
      nl: 'Slimme Wasmachines en Drogers',
    },
    description: {
      fr: 'Revues des lave-linge et sèche-linge connectés Samsung, LG, Bosch, Miele.',
      en: 'Reviews of Samsung, LG, Bosch, Miele smart washers and dryers.',
      de: 'Tests smarter Waschmaschinen und Trockner von Samsung, LG, Bosch, Miele.',
      es: 'Análisis de lavadoras y secadoras conectadas Samsung, LG, Bosch, Miele.',
      it: 'Recensioni di lavatrici e asciugatrici connesse Samsung, LG, Bosch, Miele.',
      nl: 'Reviews van slimme wasmachines en drogers Samsung, LG, Bosch, Miele.',
    },
    primaryKeyword: {
      fr: 'lave-linge connecté',
      en: 'smart washing machine',
      de: 'smarte waschmaschine',
      es: 'lavadora conectada',
      it: 'lavatrice connessa',
      nl: 'slimme wasmachine',
    },
  },

  // =================================================================
  // Meta-silo 6 — outdoor-connecte (8 categories)
  // =================================================================
  {
    slug: 'tondeuses-robots',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Tondeuses Robots',
      en: 'Robot Lawn Mowers',
      de: 'Mähroboter',
      es: 'Robots Cortacésped',
      it: 'Robot Tagliaerba',
      nl: 'Robotmaaiers',
    },
    description: {
      fr: 'Tondeuses robots Husqvarna, Worx, Gardena, Segway Navimow — avec ou sans fil périphérique.',
      en: 'Husqvarna, Worx, Gardena, Segway Navimow robot mowers — with or without boundary wire.',
      de: 'Mähroboter Husqvarna, Worx, Gardena, Segway Navimow — mit oder ohne Begrenzungskabel.',
      es: 'Robots Husqvarna, Worx, Gardena, Segway Navimow — con o sin cable perimetral.',
      it: 'Robot Husqvarna, Worx, Gardena, Segway Navimow — con o senza filo perimetrale.',
      nl: 'Husqvarna, Worx, Gardena, Segway Navimow robotmaaiers — met of zonder begrenzingsdraad.',
    },
    primaryKeyword: {
      fr: 'meilleure tondeuse robot',
      en: 'best robot lawn mower',
      de: 'bester mähroboter',
      es: 'mejor robot cortacésped',
      it: 'migliore robot tagliaerba',
      nl: 'beste robotmaaier',
    },
  },
  {
    slug: 'arrosage-connecte',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Arrosage Connecté',
      en: 'Smart Irrigation',
      de: 'Smarte Bewässerung',
      es: 'Riego Inteligente',
      it: 'Irrigazione Intelligente',
      nl: 'Slim Bewateren',
    },
    description: {
      fr: 'Programmateurs d\'arrosage connectés Gardena, Rain Bird, Eve Aqua.',
      en: 'Smart irrigation controllers from Gardena, Rain Bird, Eve Aqua.',
      de: 'Smarte Bewässerungssteuerungen Gardena, Rain Bird, Eve Aqua.',
      es: 'Controladores de riego inteligente Gardena, Rain Bird, Eve Aqua.',
      it: 'Centraline di irrigazione smart Gardena, Rain Bird, Eve Aqua.',
      nl: 'Slimme besproeiingscomputers Gardena, Rain Bird, Eve Aqua.',
    },
    primaryKeyword: {
      fr: 'programmateur arrosage connecté',
      en: 'smart irrigation controller',
      de: 'smarte bewässerungssteuerung',
      es: 'programador riego inteligente',
      it: 'centralina irrigazione smart',
      nl: 'slimme besproeiingscomputer',
    },
  },
  {
    slug: 'eclairage-exterieur',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Éclairage Extérieur Solaire Connecté',
      en: 'Smart Solar Outdoor Lighting',
      de: 'Smarte Solar-Außenbeleuchtung',
      es: 'Iluminación Exterior Solar Inteligente',
      it: 'Illuminazione Esterna Solare Intelligente',
      nl: 'Slimme Zonne-Buitenverlichting',
    },
    description: {
      fr: 'Lampes solaires connectées Philips Hue Outdoor, Ring, Netatmo pour jardin et allées.',
      en: 'Philips Hue Outdoor, Ring, Netatmo smart solar lights for garden and driveways.',
      de: 'Solarleuchten Philips Hue Outdoor, Ring, Netatmo für Garten und Einfahrt.',
      es: 'Luces solares Philips Hue Outdoor, Ring, Netatmo para jardín y entradas.',
      it: 'Luci solari Philips Hue Outdoor, Ring, Netatmo per giardino e vialetti.',
      nl: 'Zonneverlichting Philips Hue Outdoor, Ring, Netatmo voor tuin en oprit.',
    },
    primaryKeyword: {
      fr: 'éclairage extérieur connecté',
      en: 'smart outdoor lighting',
      de: 'smarte außenbeleuchtung',
      es: 'iluminación exterior inteligente',
      it: 'illuminazione esterna smart',
      nl: 'slimme buitenverlichting',
    },
  },
  {
    slug: 'portails-garages',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Portails & Portes de Garage Connectés',
      en: 'Smart Gates & Garage Doors',
      de: 'Smarte Tore & Garagentore',
      es: 'Puertas Automáticas y de Garaje Inteligentes',
      it: 'Cancelli e Garage Intelligenti',
      nl: 'Slimme Poorten en Garagedeuren',
    },
    description: {
      fr: 'Motorisations de portail et ouvre-portes de garage connectés Somfy, Meross, Chamberlain.',
      en: 'Somfy, Meross, Chamberlain smart gate and garage door openers.',
      de: 'Somfy, Meross, Chamberlain smarte Tor- und Garagentorantriebe.',
      es: 'Motores y abridores Somfy, Meross, Chamberlain para puertas y garajes.',
      it: 'Motorizzazioni cancelli e garage Somfy, Meross, Chamberlain.',
      nl: 'Somfy, Meross, Chamberlain slimme poort- en garagedeuropeners.',
    },
    primaryKeyword: {
      fr: 'ouvre-porte de garage connecté',
      en: 'smart garage door opener',
      de: 'smarter garagentorantrieb',
      es: 'abridor garaje inteligente',
      it: 'apricancello intelligente',
      nl: 'slimme garagedeuropener',
    },
  },
  {
    slug: 'robots-piscine',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'high',
    indexable: true,
    title: {
      fr: 'Robots de Piscine',
      en: 'Pool Cleaning Robots',
      de: 'Poolroboter',
      es: 'Robots de Piscina',
      it: 'Robot Piscina',
      nl: 'Zwembadrobots',
    },
    description: {
      fr: 'Robots de piscine Dolphin, Aiper, Zodiac, Bestway — nettoyage sans intervention.',
      en: 'Dolphin, Aiper, Zodiac, Bestway pool robots — hands-off cleaning.',
      de: 'Dolphin, Aiper, Zodiac, Bestway Poolroboter — Reinigung ohne Eingriff.',
      es: 'Robots de piscina Dolphin, Aiper, Zodiac, Bestway — limpieza sin intervención.',
      it: 'Robot piscina Dolphin, Aiper, Zodiac, Bestway — pulizia senza intervento.',
      nl: 'Dolphin, Aiper, Zodiac, Bestway zwembadrobots — handenvrij reinigen.',
    },
    primaryKeyword: {
      fr: 'meilleur robot de piscine',
      en: 'best pool cleaner robot',
      de: 'bester poolroboter',
      es: 'mejor robot de piscina',
      it: 'migliore robot piscina',
      nl: 'beste zwembadrobot',
    },
  },
  {
    slug: 'barbecues-connectes',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Barbecues & Planchas Connectés',
      en: 'Smart BBQs & Griddles',
      de: 'Smarte Grills & Planchas',
      es: 'Barbacoas y Planchas Inteligentes',
      it: 'Barbecue e Piastre Intelligenti',
      nl: 'Slimme Barbecues & Bakplaten',
    },
    description: {
      fr: 'Barbecues à pellets Traeger, Weber connectés et planchas connectées pour maîtriser la cuisson.',
      en: 'Traeger, Weber pellet grills and smart griddles for mastering outdoor cooking.',
      de: 'Traeger, Weber Pelletgrills und smarte Planchas für perfekte Outdoor-Kochkontrolle.',
      es: 'Barbacoas de pellets Traeger, Weber y planchas inteligentes para dominar la cocción.',
      it: 'Barbecue a pellet Traeger, Weber e piastre smart per dominare la cottura outdoor.',
      nl: 'Traeger, Weber pellet BBQs en slimme bakplaten voor perfecte buiten cooking control.',
    },
    primaryKeyword: {
      fr: 'barbecue connecté',
      en: 'smart pellet grill',
      de: 'smarter pelletgrill',
      es: 'barbacoa inteligente',
      it: 'barbecue a pellet intelligente',
      nl: 'slimme pellet bbq',
    },
  },
  {
    slug: 'stations-recharge-outdoor',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'medium',
    indexable: true,
    title: {
      fr: 'Stations de Recharge Portables',
      en: 'Portable Power Stations',
      de: 'Tragbare Powerstationen',
      es: 'Estaciones de Energía Portátiles',
      it: 'Stazioni di Ricarica Portatili',
      nl: 'Draagbare Powerstations',
    },
    description: {
      fr: 'Stations d\'énergie portables EcoFlow, Bluetti, Jackery pour camping, outdoor et coupures.',
      en: 'EcoFlow, Bluetti, Jackery portable power stations for camping, outdoor and outages.',
      de: 'EcoFlow, Bluetti, Jackery Powerstationen für Camping, Outdoor und Stromausfälle.',
      es: 'Estaciones EcoFlow, Bluetti, Jackery para camping, exterior y apagones.',
      it: 'Stazioni EcoFlow, Bluetti, Jackery per campeggio, outdoor e blackout.',
      nl: 'EcoFlow, Bluetti, Jackery powerstations voor kamperen, buiten en stroomuitval.',
    },
    primaryKeyword: {
      fr: 'station énergie portable',
      en: 'portable power station',
      de: 'tragbare powerstation',
      es: 'estación energía portátil',
      it: 'stazione energia portatile',
      nl: 'draagbaar powerstation',
    },
  },
  {
    slug: 'alarmes-exterieures',
    metaSilo: 'outdoor-connecte',
    searchVolume: 'low',
    indexable: true,
    title: {
      fr: 'Alarmes & Capteurs Extérieurs',
      en: 'Outdoor Alarms & Sensors',
      de: 'Außenalarme & Sensoren',
      es: 'Alarmas y Sensores Exteriores',
      it: 'Allarmi e Sensori da Esterno',
      nl: 'Buitenalarmen en Sensoren',
    },
    description: {
      fr: 'Alarmes et capteurs extérieurs connectés pour protéger jardin, abri et véhicules.',
      en: 'Smart outdoor alarms and sensors to protect garden, shed and vehicles.',
      de: 'Smarte Außenalarme und Sensoren zum Schutz von Garten, Schuppen und Fahrzeugen.',
      es: 'Alarmas y sensores exteriores inteligentes para jardín, cobertizo y vehículos.',
      it: 'Allarmi e sensori da esterno smart per proteggere giardino, capanno e veicoli.',
      nl: 'Slimme buitenalarmen en sensoren voor tuin, schuur en voertuigen.',
    },
    primaryKeyword: {
      fr: 'alarme extérieure connectée',
      en: 'smart outdoor alarm',
      de: 'smarter außenalarm',
      es: 'alarma exterior inteligente',
      it: 'allarme esterno intelligente',
      nl: 'slim buitenalarm',
    },
  },
] as const

export function getCategory(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug)
}

export function getCategoriesBySilo(metaSilo: string): Category[] {
  return CATEGORIES.filter((c) => c.metaSilo === metaSilo)
}

export function getIndexableCategories(): Category[] {
  return CATEGORIES.filter((c) => c.indexable)
}
